### ISSUE TITLE
ACM Queue article on Crash Consistency

### ISSUE THREAD

**Issue by msackman** [LMDB/lmdb#6]
https://queue.acm.org/detail.cfm?id=2801719

Just wondering if you've seen and read the above. I was certainly not aware of the reorderings that filesystems can do and the problems they'll cause, though I'm sure you are. Just wondering if there's anything lmdb can gain from their findings above.

**Comment by hyc** [comment]
This is the same team that published their work previously at Usenix https://www.usenix.org/conference/osdi14/technical-sessions/presentation/pillai
It has been heavily discussed on the OpenLDAP lists already (and as already noted on this repo, that is where *your* comment should have been directed). http://www.openldap.org/lists/openldap-technical/201410/msg00023.html

That team no longer mentions LMDB in their work because they have conceded that LMDB is indeed crash-proof.

**Comment by msackman** [comment]
Ahh ok, sorry for the noise then.
